/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Role } from "./Role.ts";

export type CreateUserDTO = {
    /**
     * @type string
    */
    email: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    password: string;
    role: Role;
};