/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ErrorResponse = {
    /**
     * @type string | undefined
    */
    error?: string;
    /**
     * @type integer | undefined
    */
    statusCode?: number;
    /**
     * @type string | undefined
    */
    statusText?: string;
};