/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUserDTO } from "./CreateUserDTO.ts";
import type { ErrorResponse } from "./ErrorResponse.ts";

/**
 * @description OK
*/
export type PostUsers200 = any;

/**
 * @description Bad Request
*/
export type PostUsers400 = ErrorResponse;

/**
 * @description Internal Server Error
*/
export type PostUsers500 = ErrorResponse;

/**
 * @description User data
*/
export type PostUsersMutationRequest = CreateUserDTO;

export type PostUsersMutationResponse = PostUsers200;

export type PostUsersMutation = {
    Response: PostUsers200;
    Request: PostUsersMutationRequest;
    Errors: PostUsers400 | PostUsers500;
};