/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const role = {
    RoleUser: "user",
    RoleAdmin: "admin"
} as const;

export type RoleEnumKey = (typeof role)[keyof typeof role];

export type Role = RoleEnumKey;