/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { roleSchema } from "./roleSchema.ts";

export const createUserDTOSchema = z.object({
    "email": z.string(),
"name": z.string(),
"password": z.string(),
get "role"(){
                return roleSchema
              }
    })