/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { userSchema } from "./userSchema.ts";

export const getUsersIdPathParamsSchema = z.object({
    "id": z.string().describe("User ID")
    })

/**
 * @description OK
 */
export const getUsersId200Schema = z.lazy(() => userSchema)

/**
 * @description Internal Server Error
 */
export const getUsersId500Schema = z.lazy(() => errorResponseSchema)

export const getUsersIdQueryResponseSchema = z.lazy(() => getUsersId200Schema)