/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { createUserDTOSchema } from "./createUserDTOSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";

/**
 * @description OK
 */
export const postUsers200Schema = z.unknown()

/**
 * @description Bad Request
 */
export const postUsers400Schema = z.lazy(() => errorResponseSchema)

/**
 * @description Internal Server Error
 */
export const postUsers500Schema = z.lazy(() => errorResponseSchema)

/**
 * @description User data
 */
export const postUsersMutationRequestSchema = z.lazy(() => createUserDTOSchema)

export const postUsersMutationResponseSchema = z.lazy(() => postUsers200Schema)